### ISSUE TITLE
Unable to sync with Dropbox

### ISSUE THREAD

**Issue by elsatch** [kvj/mobileorg-android#1]
When I try to setup Dropbox sync, in "MobileOrgAndroidKVJ wants to access your Dropbox account" screen, I'm getting an error: "Unable to connect Dropbox. Make sure Internet connection is enabled and try again". I open Dropbox app and it's working and able to browse my files. If I open MobileOrg (not NG) I'm able to sync Dropbox, so the error seeems to be related to OAuth issues. Using Samsung Galaxy Nexus 4.0.3. If you need any file or debug information, I'll be happy to help.

**Comment by kvj** [comment]
Hi elsatch,

Thanks for reminding about this issue. Actually, I forgot to apply for production developer keys. I've already applied and as soon they approve I'll update issue. For now I'll temporarily disable app in market

**Comment by elsatch** [comment]
Thanks kvj for your fast response!  I'll keep an eye on this thread. I'd love to try your app as it seems really promising.

**Comment by kvj** [comment]
elsatch,

Dropbox has approved application, please try to login to dropbox again, if you'll have any problems please let me know

**Comment by elsatch** [comment]
Wow, you got it! I've been able to login without problem. I'm gonna close this issue. Time to check MobileOrg new version and MobileOrgNG. Thanks Konstantin!
