### ISSUE TITLE
"Expand all" feature is too slow

### ISSUE THREAD

**Issue by eugeneb** [kvj/mobileorg-android#2]
At first, thank you for your great job!
I regard the issue with "Expand all" to be the main thing which prevents MobileOrgNG from normal use. When I try to expand all my notes MobileOrgNG freezes for a very long time - I haven't managed to wait until the end. And even relatively small subtrees consisting in just several lines expands relatively long.
Unfortunatelly for now it is impossible to avoid expanding subtree. I have found only two ways to collapse subtree. 
The first is to go through the whole cycle "Folded -> Expand -> Expand all -> Folded". But "Expand all" step is practically impossible.
The second way is to switch to another application and then switch to MobileOrgNG again. After this all the tree would be collapsed again. But I suggest this to be a bug itself.
If it is a problem to speedup expanding all sintered now, maybe it is worth to disable this feature? Say, with using special option in menu.
This issue prevents MobileOrgNG from being usable.
So as for now I believe the only usable MobileOrg implementation to be Matburt/MobileOrg-0.5.2 (all the latter versions also were unusable for different reasons).

**Comment by kvj** [comment]
Which device do you use? 
How many entries do you have in your tree?

**Comment by eugeneb** [comment]
I'm using HTC IncredibleS (Quallcomm 1GHz), Android-2.3.5, MobileOrgNG-0.0.2.1. My org file has 18600 lines. But even for subtree with some tenth lines "Expand all" is slow.

**Comment by kvj** [comment]
Please check version 0.0.3 from Market. I've added few indexes to DB to speedup tree expand. I've also made Expand All feature optional and configurable, you can disable it from settings screen (applied for new panes)

**Comment by eugeneb** [comment]
That's great, I saw significant speedup. Now it takes only 13 seconds to expand all my PlansGTD.org file with 18600 lines. About ten minutes was needed before - so it is speedup by two orders of magnitude. 
But this is still unacceptable for me, so now I can disable "expand all" feature, which temporarily solves the problem.

**Comment by kvj** [comment]
Thanks for the response.

Well, at this moment I think this is all we can do, because the problem is device and SQLite DB performance (tree is expanded recursively), and 13 seconds for ~15K entries - not a bad result. I'm thinking of another approach: limit number of entries displayed by few hundreds and show warning message when user will try to expand too big tree. I think it's practically useless to scroll a tree with more than 1K entries since we have search and bookmarks

**Comment by eugeneb** [comment]
Sure nobody need to view entire 16k lines. As for me personally, I don't thing "Expand all" possibility to be neccessary. Except for one situation. Sometimes it is needed to know do items has subtrees their own subtrees. Original org mode in Emacs shows this with three dots after the title which has a subtree. In MobileOrgNG there is no such marks. So when one see the list of items, it is not clear whether these items has subtrees. One way to make it clear is to use "Expand all". The second way - a mark with three dots as in Emacs. But now with "Expand all" feature disabled I had to check each item one by one. So a mark of hidden subtree is highly desirable.

**Comment by eugeneb** [comment]
New async collapse/expand feature in 0.0.4 version solved the problem with big files.
