### ISSUE TITLE
MONG should be usable right after installation

### ISSUE THREAD

**Issue by vovkav** [kvj/mobileorg-android#21]
should be immediately usable after installation. Right now it says 'db error' on creating a new capture.

Plz, take care of those, that  do not want to install emacs or some other complex desktop 

Org Files should be created automatically If not present

**Comment by kvj** [comment]
Unfortunately, I don't have enough resources to fully support this project, but I'd like to answer:  
No, IT SHOULDN'T be usable.
Before telling what application should do and what shouldn't, first read this http://orgmode.org/org.html#MobileOrg and keep in mind that MobileOrgNG is a companion application and nothing else. It was designed for such purpose and it does it.
