### ISSUE TITLE
It is impossible to edit body a of a note

### ISSUE THREAD

**Issue by eugeneb** [kvj/mobileorg-android#3]
I haven't managed to edit a body of a note. Even for records with body already existing it is impossible to edit the body - only the title, TODO state, priority, tags, but not the body. There is no such field in "Edit" screen. The same thing in "Capture" screen. It is only possible to create a title of a note, not a body.
MobileOrgNG-0.0.2.1, Android-2.3.5.

**Comment by kvj** [comment]
Click on any text entry, then select "edit" from action bar or menu to edit.
If you want to add new text entry to existing outline - select (click) on outline and press + sign ("add text" entry in menu) to add new text note to outline

Selected entry is displayed as italic

**Comment by eugeneb** [comment]
Maybe there is some misunderstanding. I regard any note to consist of: title, body, TODO state, tags and priority.In emacs it looks like:
- TODO [#A] The title  :the tag:
  
  The body
- The next title

It is possible to edit any field except from "the body". There is simply no such field in MobileOrgNG edit screen.

**Comment by kvj** [comment]
Well,
Please answer following questions:

Can you see "The body" when you expand "The title" outline?
When you tap on "The body" does the font becomes italic?
When "The body" is selected(italic font) and you run "Edit" action, does the edit dialog open?

**Comment by eugeneb** [comment]
1. Yes, I can see "the body" when I expand outline.
2. When I tap on "the body" the font does becomes italic.
   Here is the screenshot: http://s006.radikal.ru/i214/1201/da/ad6d665047d3.jpg
3. When I run "edit" the edit dialog appears. The screenshot:
    http://i026.radikal.ru/1201/8a/c5b17722b0c4.jpg
   As you can see there are all fields except from "the body". The bottom half of this screen is black, evidently it is a place for "the body", but I can't see and edit it. For capture screen situation is the same. "The body" is not editable at all and I only can see it in outline mode.
   Sorry for the bad screenshots, I haven't found a screenshot program for unrooted phone yet.

**Comment by kvj** [comment]
Thanks for the response.

> 1. When I tap on "the body" the font does becomes italic. Here is the screenshot:
>    From this screenshot I can see you selected "PlantsGTD.org" entry (which is read-only because it's filename), but not "The body", is it correct? To edit "The body", you need to tap on "The body" first
> 2. When I run "edit" the edit dialog appears
>    The dialog is shown on screenshot is correct, but this dialog doesn't allow to edit entry body, as a part of MobileOrgNG's design, "The title" and "The body" are two different elements, which are connected to each other, of course, but edit is done separately. As far as I remember this is different from original MobileOrg, but this allows to edit plain list entries, one entry at a time, like outlines.

**Comment by eugeneb** [comment]
My fault - I have sent a wrong screenshot. The right one here: http://i008.radikal.ru/1201/5a/0dbfbcda6ff2.jpg

Now I understand - it is a conceptual difference from Matburt/mobileorg. "The body" is a separate record. Now everything is clear. Thank you for explanation.
