### ISSUE TITLE
Wrong agenda hierarchy

### ISSUE THREAD

**Issue by eugeneb** [kvj/mobileorg-android#4]
There is a problem in Agenda Views.
I'm using heavily custom agenda views. And it seems agenda views are displayed incorrectly in MobileOrgNG.

I prepared an example to show this. In "PlansGTD.org" I have some tasks with three different tags - FirstGroup, SecondGroup and ThirdGroup: http://pastebin.com/dsbBsHJ7.

I want to have three custom agenda views, each for tasks with particular tag. So in my ".emacs" file I set this:

(setq org-agenda-custom-commands
    '(
      ("b" "MobileOrg"
       ((agenda)
    (tags-todo "FirstGroup"  ((org-agenda-overriding-header "First group")))
    (tags-todo "SecondGroup"  ((org-agenda-overriding-header "Second group")))
    (tags-todo "ThirdGroup"  ((org-agenda-overriding-header "Third group"))))))
(setq org-mobile-agendas (quote ("b")))

So in MobileOrg I should see three groups of tasks organized in corresponding subtrees. In Matburt/MobileOrg this works fine.
But in MobileOrgNG I have a problem. The hierarchy is completely wrong. It can be seen in this screenshot: http://s018.radikal.ru/i505/1201/d0/21d680a9bc4e.jpg

One can see three items with subtrees: "First group", "Second group" and "Third group". But each item has a subtree with only one (the first) task. The rest of all tasks are placed on the same hierarchy level as task groups.

 In the photo "First group" subtree is expanded and it has only one item in it's subtree - "Task 1.1". The groups "Second group" and "Third group" has their own subtrees with only one task in each - "Task 2.1" and "Task 3.1" respectively. But these subtrees are collapsed.

**Comment by kvj** [comment]
Thanks for the report.

First of all, please check agendas.org (generated by org-mobile-push) file in MobileOrg stage directory. Does it have correct tree structure? If tree is correct, could you please share this file or part of it with me?

Thanks in advance

**Comment by eugeneb** [comment]
agendas.org has correct structure as I see. Here it is: http://pastebin.com/tBFBF3G5

There are no empty lines between first items in subtrees and corresponding titles of these subtrees, while the rest items separated by empty lines. Maybe it is a reason?

**Comment by kvj** [comment]
Thanks,

No, shouldn't be the reason. I'll check it out

**Comment by kvj** [comment]
Ah, you have empty lines just after outline but before PROPERTIES drawer. That's the point. I'll fix this

**Comment by kvj** [comment]
Fixed in 0.0.4. Please update from Market

**Comment by eugeneb** [comment]
I can confirm the problem has been solved.Thank you.
